# Generated by Django 4.1.7 on 2023-05-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weekday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekday.week')),
            ],
        ),
    ]
